### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by chapchon819** [chapchon819/nekospot#144]
まだバグを修正しきれていませんが、一旦提出させたいただきます。
ご確認よろしくお願いいたします。
なお、機能イメージの動画がマークダウンだとうまく表示されないため、gifにて添付させていただいております。

## 各種情報
サービス名：NekoSpot
サービスURL：https://nekospot.jp

※スポットが表示されるのは現時点で東京都と兵庫県のみです。

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] LINEログイン
- [x] Google Places APIでスポット詳細情報の取得・表示（あらかじめDBに保存しておく）
- [x] Google Maps JavaScript APIで地図表示
- [x] Google Geolocation APIで現在地周辺の猫スポットを取得
- [x] 検索機能（カテゴリー・地域から）
- [x] スポット詳細表示
  - [ ]Instagram graph APIで関連投稿を取得し表示させる
- [x] お気に入り登録機能
- [ ]LINE通知機能
  - リマインド
  - レビュー依頼通知
- [x]レビュー投稿機能
- [ ]みんなの猫スポット投稿・編集・削除機能
- [x]レスポンシブ
- [ ]Twitterシェア

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
【作らなくなった機能】
- Instagram graph APIを用いた機能（ビジネス認証をしないと本番環境で利用できないため）
- LINE通知機能(本リリースにて実装予定)
- みんなの猫スポット投稿・編集・削除機能(本リリースにて実装予定)
- Twitterシェア(本リリースにて実装予定)

【追加した機能】
- Googleログイン
- フリーワード検索
- 一覧から検索
- レビュー一覧から検索
- ユーザー編集機能
- ログインモーダル
- MAPで選択した地域にフォーカスする機能

### Googleログイン
https://i.gyazo.com/355aef43e0df2b3b04d8e766f428b7ce.gif

### LINEログイン
https://i.gyazo.com/9888fa891550eac1ab4935e2d145e728.gif

### 現在地を表示＆ピンから10kmのスポット一覧表示
https://i.gyazo.com/054cf7d43eedbb9ec0f6bb804646c065.gif

### カテゴリ検索
https://gyazo.com/cee2bd9701ee27201ad5a105453b8cbb

### MAPで選択した地域にフォーカスする機能
https://i.gyazo.com/379d76cf6318f4c13cd09fc09c36663f.gif

### お気に入り機能
https://i.gyazo.com/a111a232629f5d52a993f726ce7d35ea.gif

### レビュー投稿機能
https://i.gyazo.com/639f031de7ec7c6fb03ab381d06adf60.gif

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
