### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by chapchon819** [chapchon819/nekospot#66]
ご確認よろしくお願いいたします。
### MVPリリース
- [ ] LINEログイン
- [ ] Googleログイン
- [ ] ログアウト
- [ ] マイページ
- [ ] Google Map API
- Geocording API
- PlacesAPI
- Distination API
- オートコンプリート
- [ ] 検索機能
- [ ] レビュー機能
- [ ] お気に入り登録・削除
### 本リリース
- [ ] Twitterシェア
- [ ] Google Map Distination APIで経路表示
- [ ] スポット詳細画面で近隣のスポットを表示
- [ ] LINEレビュー依頼
- [ ] 猫スポット投稿機能
- [ ] 猫スポット編集・削除機能
- [ ] いいね・コメント機能
- [ ] PWA化
- [ ] (できれば)イベント(譲渡会)検索機能

### READMEからの変更点
イベント関連の機能は、Instagram Graph APIが本番環境で使用できない事がわかった為、一旦なしで進めます。

**Comment by Tsuchiya2** [comment]
<img width="677" alt="image" src="https://github.com/chapchon819/nekospot/assets/61481161/3676d392-4f47-45b5-998a-52c0c22ee771">


projectsにアクセスにしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態でご提出お願いいたします。

**Comment by chapchon819** [comment]
大変失礼いたしました。
projectのリンクを追加し再提出しましたので、ご確認いただけますと幸いです。
よろしくお願いいたします。

**Comment by tarakish** [comment]
確認できました👍
細かめの粒度にブレイクダウンされている & Issueの内容もタスク化されていて良いですね。LGTMです！
ストーリーポイントが5のものは取り組む前に調査し、さらに細かくできると良いと思います。

**Comment by chapchon819** [comment]
ご確認ありがとうございます！
承知しました！ストーリーポイント5のものは調査を行ってから取り組むようにします。
